const dataSet = [
    ['Html', 'https://pixabay.com/es/', 'fondos', 'imágenes gratis para fondos de pantalla'],
    ['Css', 'https://www.w3schools.com/cssref/', 'css - reference', 'referencia de css'],
    ['Html','https://fontawesome.com/', 'iconos', 'iconos gratis de todo tipo'],
    ['Spinner','https://cssloaders.github.io/', 'spinner', 'spinners gratis de todo tipo'],
    ['Paleta colores','https://color.adobe.com/es/create/color-wheel', 'paletas - colores', 'generador de paletas de colores gratis'],
    ['Plantillas web','https://www.w3schools.com/w3css/w3css_templates.asp', 'plantillas', 'plantillas gratis de todo tipo'],
    ['Plantillas web','https://plantillashtmlgratis.com/', 'plantillas', 'plantillas gratis de todo tipo'],
    ['Logos y gráficos','https://es.cooltext.com/', 'logos - gráficos', 'generador de logos y gráficos gratis'],
    ['Logos con IA','https://www.logoai.com/', 'logos IA', 'generador de logos y branding con inteligencia artificial'],
    ['Paleta colores','https://color.adobe.com/es/create/image', 'extractor de colores', 'extrae paletas de colores de una imagen'],
    ['Eliminar Fondo imagen','https://www.remove.bg/es', 'eliminar fondo - imagenes', 'elimina el fondo de una imagen'],
    ['Css','https://getbootstrap.com/docs/5.0/getting-started/introduction/', 'bootstrap 5 - css', 'framework css de estilos web'],
    ['Imagenes','https://www.pexels.com/es-es/', 'imagenes gratis', 'imagenes gratis para fondos de pantalla'],
    ['Imagenes','https://pixabay.com/es/', 'imagenes gratis', 'imagenes gratis para fondos de pantalla'],
    ['Escalador imagenes','https://www.upscale.media/es', 'imagenes - cambio escala', 'cambia la escala de una imagen'],
    ['Apis Públicas','https://publicapis.dev/', 'apis publicas', 'apis publicas de todo tipo'],
    ['iconos','https://www.iconfinder.com/', 'iconos', 'iconos gratis de todo tipo'],
    ['IA','https://aifindy.com/', 'IA', 'recursos de inteligencia artificial'],
];
